export enum InteractionType {
  SHORTLISTED = 'shortlisted',
  BLOCKED = 'blocked',
  DECLINED = 'declined',
  IGNORE = 'ignore',
  MATCH_REQUEST_SENT = 'match_request_sent',
  MATCH_REQUEST_CANCELLED = 'match_request_cancelled',
  MATCH_REQUEST_ACCEPTED = 'match_request_accepted',
  MATCH_REQUEST_DECLINED = 'match_request_declined',
  UNBLOCKED = 'unblocked',
  REMOVED_FROM_SHORTLIST = 'removed_from_shortlist',
  REMOVED_FROM_ACCEPTEDLIST = 'removed_from_acceptedlist',
  REMOVED_FROM_DECLINEDLIST = 'removed_from_declinedlist',
  VIEW = 'view',
}
