import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import "react-datetime/css/react-datetime.css";
import AuthProviderWrapper from "@/components/auth/AuthProvider";
import { ToastProvider } from "@/contexts/ToastScope";
import ChatProviderWrapper from "@/components/chat/ChatProvider";
import OfflineModal from "@/components/modal/OfflineModal";

export const lexendDeca = Lexend_Deca({
  subsets: ["latin"], // Specify the desired subsets
  display: "swap", // Recommended for better performance
  variable: "--font-lexend-deca", // Optional: Define a CSS variable for easier styling
});

export const metadata: Metadata = {
  title: "Matrimony website",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} antialiased`}>
        <AuthProviderWrapper>
          <ChatProviderWrapper>
            <ToastProvider>{children}</ToastProvider>
          </ChatProviderWrapper>
        </AuthProviderWrapper>
        <OfflineModal />
      </body>
    </html>
  );
}
