import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import Header from "@/components/Header";
import AuthProviderWrapper from "@/components/auth/AuthProvider";

export const lexendDeca = Lexend_Deca({
  subsets: ["latin"], // Specify the desired subsets
  display: "swap", // Recommended for better performance
  variable: "--font-lexend-deca", // Optional: Define a CSS variable for easier styling
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} antialiased`}>
        <AuthProviderWrapper>
          <NextTopLoader
            color="white"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            zIndex={9999}
            template={`<div class="fixed top-0 left-0 h-[3px] w-full z-[9999] bg-gradient-to-r from-indigo-600 to-pink-500 animate-gradientMove" role="bar"></div>`}
          />
          <Header />
          <div className="mt-[70px] mb-10">{children}</div>
        </AuthProviderWrapper>
      </body>
    </html>
  );
}
